Feature/no more open struct
CO2Management/tukey pull request #15
Opened 2022-06-28 12:19 UTC by arjan0307

2022-07-01 09:01 UTC, kreintjes requested changes
Zie code comments. Met name die empty file mag wel mag.

2022-07-01 09:01 UTC, kreintjes commented on lib/tukey/data_set/label.rb
> +    end
Je voegt hieronder alsnog een empty file serialize_options toe. Die kan weg lijkt me.

2022-07-01 09:01 UTC, kreintjes commented on tukey.gemspec
> +  spec.add_dependency 'activesupport'
Blijft wel een beetje loos voelen om heel activesupport alleen hiervoor aan die Gem toe te voegen. Maar goed, zolang co2m het enige is wat het gebruikt boeit het ook niet veel :p

2022-07-01 11:48 UTC, kreintjes commented on lib/tukey/data_set/label.rb
> +require 'active_support/ordered_options'
De benchmark van de verschillen tussen openstruct, OrderedOptions en Hash opnemen in de commit message zou hier ook niet verkeerd zijn.

2022-07-05 18:22 UTC, arjan0307 commented
Ik heb deze wijzigingen: `merge!`, empty file verwijderen en de commit message aanpassen meteen ge-amend.

2022-07-06 10:55 UTC, kreintjes approved these changes
Code approved. Ik zal nog even functioneel testen op de review app bij co2m als die er weer is.

2022-07-06 17:09 UTC, merged